# Generated by Django 5.0.4 on 2024-04-29 15:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(default=uuid.uuid1, max_length=20, unique=True),
        ),
    ]
